export const GET_CONTACTS_LOAD = "GET_CONTACTS_LOAD";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const ADD_CONTACT_SUCCESS = "ADD_CONTACTS_SUCCESS";
export const ADD_CONTACT_FAIL = "ADD_CONTACTS_FAIL";

export const TOOGLE_TRUE = "TOOGLE_TRUE";
export const TOOGLE_FALSE = "TOOGLE_FALSE";

export const GET_CONTACT_LOAD = "GET_CONTACT_LOAD";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAIL = "GET_CONTACT_FAIL";

export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACTS_SUCCESS";
export const EDIT_CONTACT_FAIL = "EDIT_CONTACTS_FAIL";
